### ISSUE TITLE
豆腐

### ISSUE THREAD

**Issue by exzhawk** [exzhawk/SDYGServer#14]
钢豆腐锭想干嘛,做个EIO机械核心是要我等半小时通过各种复杂手段才能制造出来么,想显得机器机器珍贵让我们去农家乐吧
快速造(压)豆腐的方法呢,自然压最原生态对吧.
高炉1280tick做钢豆腐齿轮做机械核心做常用机器不浪费时间么.
豆腐宝石的获取方式单一,矿石密度暂时已知罕见,EIO的基础电容不会少用到
SFM的基础方块需要秘银豆腐服方块,还1:16比例.想把sfm打造成传说级物品么.
钻石豆腐一粒一粒做,zz吧.

**Comment by Yoshisky** [comment]
恩，那你就玩农家乐吧。豆腐是圣地亚哥世界的灵魂mod，说什么都不会变的，前几周目都知道这尿性还在这抱怨有用吗？
