### ISSUE TITLE
[Feature Request]提议让人物死亡的区域附近的怪刷掉

### ISSUE THREAD

**Issue by wishforgood** [exzhawk/SDYGServer#28]
之前好像有这种mod，不清楚是啥，具体就是人物被杀之后那附近的怪都会刷没，这样/back回去就能捡东西不会被守尸。。。最近在地狱不停死亡捡尸体浪费太多时间了，，，求加这功能

**Comment by Yoshisky** [comment]
mod？不是插件吗。。。spawnprotect

**Comment by wishforgood** [comment]
哦。。。总之求。
