### ISSUE TITLE
认为mod没用不加的...

### ISSUE THREAD

**Issue by Pr-wing** [exzhawk/SDYGServer#3]
认为mod没用不加的,我可以改合成,改到涉及部分要用到的方块/物品之中,具有唯一性,而且更难,可参考豆腐mod.
认为modOP的,没修改到其他mod的你们可以不玩那mod,涉及到其他modconfig里关掉,关不掉再跟我说删mod.特附上一图.
![qq 20160821225110](https://cloud.githubusercontent.com/assets/12102626/17837899/d93fc4cc-67f1-11e6-89a8-6af49cf60d0e.png)

最后再提一点,在开这周目的时候,就没人说过要肛,也没说过要改难合成表,更加没人说过一天肛完mc好烦恼,求你让你替我们解决这个烦恼,你整合这个包包完所有工作我也很感激,但不要把你自己的意志强加到我身上.

1版,我打算日更的节奏(  
2016-08-21

**Comment by exzhawk** [comment]
split into #8 #9 #10 #11 #12 #13 #14 #15 #16 #17 #18 #19 #20 #21 #22 #23 #24 #25

**Comment by Yoshisky** [comment]
卧槽，以后这种issue全家桶直接打死发帖的
