### ISSUE TITLE
关于新家房屋结构规范的讨论

### ISSUE THREAD

**Issue by wishforgood** [exzhawk/SDYGServer#31]
出于可拓展性，空间节约性，后期寻物便捷性等因素的考量，拟建造这样的房屋：
基本组成单元：16x16x8的神圣橡木板区块
结构：巫师塔状，横向纵向可拓展
横向拓展上限：五个区块
暂不建议房顶、阳台等建筑以影响空间利用效率，可内部自行改造以供自嗨

**Comment by exzhawk** [comment]
和区块对齐啊

**Comment by Yoshisky** [comment]
自嗨可以，
趁我还没开始建筑之前你们嗨高兴点（）（）（）

**Comment by exzhawk** [comment]
一个mod/分类占一个子塔, 并且允许子塔继续向外扩展吧
主塔用来走路或者放通用的东西, 比如存储, 常用工具之类

**Comment by wishforgood** [comment]
@exzhawk 可以啊(，重构呗
