### ISSUE TITLE
请求增加暴雪（雪怪）的出现概率。。。

### ISSUE THREAD

**Issue by wishforgood** [exzhawk/SDYGServer#33]
昨天晚上刷了好久就出了4个，还特么一个棒子没掉。。。报警了，这月锭也太难做了，以后咋玩

**Comment by Yoshisky** [comment]
I'm working on it(((

**Comment by Yoshisky** [comment]
There will be 4~12 mobs in a group when spawning at night, enjoy)

**Comment by exzhawk** [comment]
blizz drop blitz items

**Comment by exzhawk** [comment]
NG
still drop wrong items
