### ISSUE TITLE
IE steel rod not available

### ISSUE THREAD

**Issue by exzhawk** [exzhawk/SDYGServer#34]
![image](https://cloud.githubusercontent.com/assets/7038938/18166194/471515d2-707c-11e6-9a05-d4913572c925.png)
![image](https://cloud.githubusercontent.com/assets/7038938/18166197/4be27f46-707c-11e6-8cb2-5ca978c1bef1.png)
![image](https://cloud.githubusercontent.com/assets/7038938/18166204/54513f1e-707c-11e6-9d6d-cde989fc3a3e.png)
loop craft dependency
rod recipe removed and not added later? https://github.com/exzhawk/SDYGServer/blob/master/scripts/IE_tfComp.zs#L150

**Comment by Yoshisky** [comment]
fixed
