### ISSUE TITLE
Ocular organization name

### ISSUE THREAD

**Issue by jonysy** [exzhawk/SDYGServer#36]
Hello,

Apologies for submitting an issue here, but I have no other means of contacting you. You currently have ownership of the `ocular` organization name and there are no recent commits -- would you be willing to transfer the ownership to me?

Kind Regards,

Jony

**Comment by exzhawk** [comment]
Sorry, but that organization name is still in use.

**Comment by jonysy** [comment]
Ok, no problem :)
